name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linux-gpp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show compiler
        run: g++ --version

      - name: Run local CI script
        run: bash tools/run_local_ci.sh
